<!-- Invoice Footer Partial -->
<table style="width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 11px;">
    <tr>
        <td style="width: 55%; vertical-align: top; padding-right: 15px;">
            <!-- Amount in Words -->
            <div style="border: 1px solid #cbd5e1; border-radius: 4px; padding: 8px; background-color: #f8fafc; margin-bottom: 12px;">
                <span style="font-size: 10px; font-weight: bold; text-transform: uppercase; color: #64748b;">Amount in Words:</span>
                <div style="font-weight: bold; color: #1e293b; margin-top: 2px;">{{ $amountInWords }}</div>
            </div>

            <!-- Terms & Conditions -->
            <div style="font-size: 10px; color: #64748b; line-height: 1.4;">
                <strong>Terms & Conditions:</strong><br>
                1. Goods once sold will not be taken back or exchanged.<br>
                2. Subject to local jurisdiction.<br>
                3. This is a computer-generated tax invoice.
            </div>
        </td>

        <td style="width: 45%; vertical-align: top;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                <tr>
                    <td style="padding: 3px 0; color: #64748b;">Subtotal:</td>
                    <td style="padding: 3px 0; text-align: right; font-weight: 600;">₹{{ number_format($sale->subtotal, 2) }}</td>
                </tr>
                @if($sale->item_discount > 0)
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">Item Discount:</td>
                        <td style="padding: 3px 0; text-align: right; color: #d97706;">-₹{{ number_format($sale->item_discount, 2) }}</td>
                    </tr>
                @endif
                @if($sale->invoice_discount > 0)
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">Invoice Discount:</td>
                        <td style="padding: 3px 0; text-align: right; color: #d97706;">-₹{{ number_format($sale->invoice_discount, 2) }}</td>
                    </tr>
                @endif
                @if($gstType == 1)
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">CGST Amount:</td>
                        <td style="padding: 3px 0; text-align: right;">₹{{ number_format($sale->cgst_amount, 2) }}</td>
                    </tr>
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">SGST Amount:</td>
                        <td style="padding: 3px 0; text-align: right;">₹{{ number_format($sale->sgst_amount, 2) }}</td>
                    </tr>
                @else
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">IGST Amount:</td>
                        <td style="padding: 3px 0; text-align: right;">₹{{ number_format($sale->igst_amount, 2) }}</td>
                    </tr>
                @endif
                <tr>
                    <td style="padding: 3px 0; color: #64748b;">Total Tax:</td>
                    <td style="padding: 3px 0; text-align: right; font-weight: 600;">₹{{ number_format($sale->tax_amount, 2) }}</td>
                </tr>
                @if($sale->round_off != 0)
                    <tr>
                        <td style="padding: 3px 0; color: #64748b;">Round Off:</td>
                        <td style="padding: 3px 0; text-align: right;">₹{{ number_format($sale->round_off, 2) }}</td>
                    </tr>
                @endif
                <tr style="border-top: 2px solid #0f172a; border-bottom: 2px solid #0f172a; font-size: 14px;">
                    <td style="padding: 6px 0; font-weight: bold; color: #0f172a;">Grand Total:</td>
                    <td style="padding: 6px 0; text-align: right; font-weight: 800; color: #4f46e5;">₹{{ number_format($sale->grand_total, 2) }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table style="width: 100%; margin-top: 40px; font-size: 11px;">
    <tr>
        <td style="width: 50%; color: #64748b;">
            Generated By: <strong>{{ $generatedBy }}</strong><br>
            Print Date: {{ date('d/m/Y H:i') }}
        </td>
        <td style="width: 50%; text-align: right; vertical-align: bottom;">
            <div style="border-top: 1px solid #94a3b8; display: inline-block; width: 180px; text-align: center; padding-top: 4px; font-weight: 600; color: #334155;">
                Authorized Signatory
            </div>
        </td>
    </tr>
</table>
